# Домашнє завдання  
## Основи Python, колекції та перше знайомство з Pandas

**Курс:** Data Analyst  
**Модуль:** Основи роботи з даними в Python  
**Уроки:** 1–2

---

## Правила виконання

1. Кожне завдання виконуй у відповідній комірці.
2. Створюй саме ті змінні, які вказані в умові.
3. Не змінюй назви змінних.
4. Запускай комірки зверху вниз.
5. Для завдань з `input()` у цьому ноутбуці використовуємо імітацію введення через рядкові змінні, щоб перевірка могла працювати автоматично.

---

## Контекст

Ти працюєш з невеликими даними про продажі менеджерів.  
Спочатку потрібно закріпити базовий Python: типи даних, перетворення, введення/виведення, списки, словники, множини та прості цикли.  
Після цього потрібно виконати базові дії з DataFrame у Pandas.

## Початкові дані

In [115]:
managers = ['Anna', 'Bohdan', 'Olena', 'Ivan']
regions = ['Kyiv', 'Lviv', 'Kyiv', 'Odesa']
sales_q1 = [15000, 12000, 22000, 9500]
sales_q2 = [17000, 11000, 24000, 14000]

## Частина 1. Виведення даних і типи

### Завдання 1

Створи змінну `welcome_message`.

У ній має бути текстове повідомлення:

`Python for Data Analysis`

Після створення змінної виведи її через `print()`.

In [116]:
# Завдання 1

welcome_message = 'Python for Data Analysis'
print(welcome_message)

Python for Data Analysis

### Завдання 2

Створи змінну `students_count` зі значенням `28`.

Створи змінну `students_count_type`, у яку запиши тип змінної `students_count`.

Використай `type()`.

In [117]:
# Завдання 2

students_count = 28
students_count_type = type(students_count)
print(students_count, students_count_type)

28 <class 'int'>

### Завдання 3

Створи змінну `conversion_rate` зі значенням `0.17`.

Створи змінну `conversion_rate_type`, у яку запиши тип змінної `conversion_rate`.

In [118]:
# Завдання 3

conversion_rate = 0.17
conversion_rate_type = type(conversion_rate)
print(conversion_rate, conversion_rate_type)

0.17 <class 'float'>

### Завдання 4

Створи змінну `manager_name` зі значенням `'Anna'`.

Створи змінну `manager_name_type`, у яку запиши тип змінної `manager_name`.

In [119]:
# Завдання 4

manager_name = 'Anna'
manager_name_type = type(manager_name)
print(manager_name, manager_name_type)

Anna <class 'str'>

### Завдання 5

Створи змінну `is_active` зі значенням `True`.

Створи змінну `is_active_type`, у яку запиши тип змінної `is_active`.

In [120]:
# Завдання 5

is_active = True
is_active_type = type(is_active)
print(is_active, is_active_type)

True <class 'bool'>

## Частина 2. Перетворення типів

### Завдання 6

Є змінна `age_input`.

Вона імітує значення, яке користувач ввів через `input()`.

Перетвори `age_input` у ціле число та збережи результат у змінну `age`.

In [121]:
# Завдання 6

age_input = "34"
age = int(age_input)
print(age, type(age))

34 <class 'int'>

### Завдання 7

Є змінна `price_input`.

Перетвори її у число з дробовою частиною та збережи результат у змінну `price`.

In [122]:
# Завдання 7

price_input = "19.99"
price = float(price_input)
print(price, type(price))

19.99 <class 'float'>

### Завдання 8

Є змінна `orders_count`.

Перетвори її у рядок та збережи результат у змінну `orders_count_str`.

In [123]:
# Завдання 8

orders_count = 125
orders_count_str = str(orders_count)
print(orders_count_str, type(orders_count_str))

125 <class 'str'>

### Завдання 9

Є змінна `empty_value`.

Перетвори її у логічний тип та збережи результат у змінну `empty_value_bool`.

In [124]:
# Завдання 9

empty_value = ""
empty_value_bool = bool(empty_value)
print(empty_value_bool, type(empty_value_bool))

False <class 'bool'>

### Завдання 10

Є змінна `number_as_text`.

У ній збережено дробове число у вигляді рядка.

Перетвори це значення у ціле число через проміжне перетворення у `float`.

Результат збережи у змінну `number_as_int`.

In [125]:
# Завдання 10

number_as_text = "3.14"
number_as_text = float(number_as_text)
number_as_int = int(number_as_text)
print(number_as_int)

3

## Частина 3. Арифметика та логічні умови

### Завдання 11

Є змінні `sales` і `target`.

Створи змінну `target_reached`, яка дорівнює `True`, якщо `sales` більше або дорівнює `target`.

In [126]:
# Завдання 11

sales = 12000
target = 10000
target_reached = sales >= target
print(target_reached)

True

### Завдання 12

Є змінна `sales`.

Створи змінну `sales_category`.

У ній має бути:
- `'high'`, якщо `sales >= 15000`;
- `'medium'`, якщо `sales >= 10000`;
- `'low'`, якщо продажі менші за `10000`.

Використай `if / elif / else`.

In [127]:
# Завдання 12

sales = 12000
if sales < 10000:
  sales_category = 'low'
elif sales >= 15000:
  sales_category = 'high'
else:
  sales_category = 'medium'
print(sales_category)

medium

### Завдання 13

Є змінні `has_access` і `is_active_user`.

Створи змінну `can_use_dashboard`.

Вона має дорівнювати `True`, якщо обидві умови істинні.

In [128]:
# Завдання 13

has_access = True
is_active_user = True
if has_access == True and is_active_user == True:
   can_use_dashboard = True
else:
  can_use_dashboard = False
print(can_use_dashboard)

True

### Завдання 14

Є змінні `is_admin` і `is_owner`.

Створи змінну `can_edit_project`.

Вона має дорівнювати `True`, якщо хоча б одна з умов істинна.

In [129]:
# Завдання 14

is_admin = False
is_owner = True
can_edit_project = is_owner or is_admin
print(can_edit_project)

True

## Частина 4. Списки та слайсинг

### Завдання 15

Створи змінну `managers_count`.

У ній має бути кількість елементів у списку `managers`.

Використай `len()`.

In [130]:
# Завдання 15

managers_count = len(managers)
print(managers_count)
# four managers (managers = ['Anna', 'Bohdan', 'Olena', 'Ivan'])

4

### Завдання 16

Створи змінну `first_manager`.

У ній має бути перший елемент списку `managers`.

In [131]:
# Завдання 16

first_manager = managers[0]
print(first_manager)

Anna

### Завдання 17

Створи змінну `last_manager`.

У ній має бути останній елемент списку `managers`.

In [132]:
# Завдання 17

last_manager = managers[-1]
print(last_manager)

Ivan

### Завдання 18

Створи змінну `first_two_managers`.

У ній мають бути перші два менеджери зі списку `managers`.

Використай слайсинг.

In [133]:
# Завдання 18

first_two_managers = managers[0:2]
print(first_two_managers)

['Anna', 'Bohdan']

### Завдання 19

Створи змінну `last_two_sales_q1`.

У ній мають бути останні два значення зі списку `sales_q1`.

Використай слайсинг.

In [134]:
# Завдання 19

last_two_sales_q1 = sales_q1[-2:]
print(last_two_sales_q1)
# sales_q1 = [15000, 12000, 22000, 9500]

[22000, 9500]

### Завдання 20

Створи копію списку `managers` у змінній `managers_updated`.

Додай у `managers_updated` нового менеджера `'Maria'`.

Початковий список `managers` не змінюй.

In [135]:
# Завдання 20

managers_updated = managers.copy()
managers_updated.append('Maria')
print(managers, managers_updated)

['Anna', 'Bohdan', 'Olena', 'Ivan'] ['Anna', 'Bohdan', 'Olena', 'Ivan', 'Maria']

### Завдання 21

Створи копію списку `sales_q1` у змінній `sales_q1_updated`.

Додай у `sales_q1_updated` значення `18000`.

Початковий список `sales_q1` не змінюй.

In [136]:
# Завдання 21

sales_q1_updated = sales_q1.copy()
sales_q1_updated.append(18000)
print(sales_q1_updated)

[15000, 12000, 22000, 9500, 18000]

### Завдання 22

Створи змінну `sorted_sales_q1`.

У ній має бути відсортована за зростанням копія списку `sales_q1`.

Початковий список `sales_q1` не змінюй.

In [137]:
# Завдання 22

sorted_sales_q1 = sales_q1.copy()
sorted_sales_q1.sort()
print(sorted_sales_q1)

[9500, 12000, 15000, 22000]

## Частина 5. Прості цикли

### Завдання 23

Є список `sales_q1`.

Створи змінну `total_sales_q1`.

За допомогою циклу `for` порахуй суму всіх продажів у `sales_q1`.

Не використовуй `sum()`.

In [138]:
# Завдання 23

total_sales_q1 = 0
for sale in sales_q1:
    total_sales_q1 += sale
print(f'Сума продажів: {total_sales_q1} грн')

Сума продажів: 58500 грн

### Завдання 24

Є список `sales_q1`.

Створи список `high_sales_q1`.

За допомогою циклу `for` додай у нього тільки значення, які більші за `10000`.

In [139]:
# Завдання 24

high_sales_q1 = []
for sale in sales_q1:
  if sale > 10000:
    high_sales_q1.append(sale)
print(high_sales_q1)

[15000, 12000, 22000]

### Завдання 25

Створи список `manager_messages`.

За допомогою циклу `for` додай у нього повідомлення для кожного менеджера зі списку `managers`.

Формат повідомлення:

`Manager: Anna`

Для кожного імені має бути окремий рядок у списку.

In [140]:
# Завдання 25

manager_messages = []
for manager in managers:
  manager_messages.append(f'Manager: {manager}')
print(manager_messages)

['Manager: Anna', 'Manager: Bohdan', 'Manager: Olena', 'Manager: Ivan']

### Завдання 26

Створи змінну `counter_result`.

За допомогою циклу `while` збільшуй лічильник від `0` до `5`.

У результаті `counter_result` має містити фінальне значення лічильника.

In [141]:
# Завдання 26

counter_result = 0
while counter_result < 5:
  # print('counter_result :', counter_result)
  counter_result += 1
print('counter_result :', counter_result)

counter_result : 5

## Частина 6. Словники

### Завдання 27

Створи словник `manager_region`.

У ньому:
- ключ — ім'я менеджера;
- значення — регіон менеджера.

Створи словник вручну на основі списків `managers` і `regions`.

In [142]:
# Завдання 27

manager_region = {
    'Anna': 'Kyiv',
    'Bohdan': 'Lviv',
    'Olena' : 'Kyiv',
    'Ivan' : 'Odesa'
}
print(manager_region)

{'Anna': 'Kyiv', 'Bohdan': 'Lviv', 'Olena': 'Kyiv', 'Ivan': 'Odesa'}

### Завдання 28

Створи змінну `anna_region`.

У ній має бути регіон менеджера `'Anna'`.

Використай словник `manager_region`.

In [143]:
# Завдання 28

anna_region = manager_region['Anna']
print(anna_region)

Kyiv

### Завдання 29

Створи змінну `petro_region`.

Спробуй отримати регіон менеджера `'Petro'` через `.get()`.

Якщо такого ключа немає, має повернутися значення `'Unknown'`.

In [144]:
# Завдання 29

petro_region = manager_region.get('Petro', 'Unknown')
print(petro_region)

Unknown

### Завдання 30

Створи копію словника `manager_region` у змінній `manager_region_updated`.

Додай до словника `manager_region_updated` пару:

`'Maria': 'Lviv'`

In [145]:
# Завдання 30

manager_region_updated = manager_region.copy()
manager_region_updated.update({'Maria': 'Lviv'})
print(manager_region_updated)

{'Anna': 'Kyiv', 'Bohdan': 'Lviv', 'Olena': 'Kyiv', 'Ivan': 'Odesa', 'Maria': 'Lviv'}

## Частина 7. Множини

### Завдання 31

Створи змінну `unique_regions`.

У ній має бути множина унікальних регіонів зі списку `regions`.

In [146]:
# Завдання 31

unique_regions = set(regions)
print(unique_regions)

{'Odesa', 'Kyiv', 'Lviv'}

### Завдання 32

Є дві множини: `required_skills` і `candidate_skills`.

Створи змінну `matched_skills`.

У ній мають бути навички, які є в обох множинах.

In [147]:
# Завдання 32

required_skills = {'python', 'sql', 'pandas'}
candidate_skills = {'python', 'excel', 'sql'}
matched_skills = required_skills & candidate_skills
print(matched_skills)

{'python', 'sql'}

### Завдання 33

Створи змінну `missing_skills`.

У ній мають бути навички, яких не вистачає кандидату.

In [148]:
# Завдання 33

missing_skills = required_skills - candidate_skills
print(missing_skills)

{'pandas'}

## Частина 8. Pandas

У цій частині завдання залишаються на рівні першого знайомства з DataFrame.

### Завдання 34

Імпортуй Pandas як `pd`.

Створи DataFrame `df` з початкових списків:

- `manager`
- `region`
- `sales_q1`
- `sales_q2`

In [149]:
# Завдання 34

import pandas as pd
df = pd.DataFrame({
  'manager': managers,
  'region': regions,
  'sales_q1': sales_q1,
  'sales_q2': sales_q2
})
df

  manager region  sales_q1  sales_q2
0    Anna   Kyiv     15000     17000
1  Bohdan   Lviv     12000     11000
2   Olena   Kyiv     22000     24000
3    Ivan  Odesa      9500     14000

### Завдання 35

Створи змінну `df_shape`.

У ній має бути форма DataFrame `df`.

In [150]:
# Завдання 35

df_shape = df.shape
df_shape

(4, 4)

### Завдання 36

Створи змінну `df_head`.

У ній мають бути перші 5 рядків DataFrame `df`.

Використай `.head()`.

In [151]:
# Завдання 36

df_head = df.head(5)
df_head

  manager region  sales_q1  sales_q2
0    Anna   Kyiv     15000     17000
1  Bohdan   Lviv     12000     11000
2   Olena   Kyiv     22000     24000
3    Ivan  Odesa      9500     14000

### Завдання 37

Додай до DataFrame `df` стовпець `total`.

Він має дорівнювати сумі `sales_q1` і `sales_q2`.

In [152]:
# Завдання 37

df['total'] = df['sales_q1'] + df['sales_q2']
df

  manager region  sales_q1  sales_q2  total
0    Anna   Kyiv     15000     17000  32000
1  Bohdan   Lviv     12000     11000  23000
2   Olena   Kyiv     22000     24000  46000
3    Ivan  Odesa      9500     14000  23500

### Завдання 38

Додай до DataFrame `df` стовпець `growth_pct`.

Формула:

```python
(sales_q2 - sales_q1) / sales_q1 * 100
```

Результат округли до одного знаку після коми.

In [153]:
# Завдання 38

df['growth_pct'] = ((df['sales_q2'] - df['sales_q1']) / df['sales_q1'] * 100).round(1)
df

  manager region  sales_q1  sales_q2  total  growth_pct
0    Anna   Kyiv     15000     17000  32000        13.3
1  Bohdan   Lviv     12000     11000  23000        -8.3
2   Olena   Kyiv     22000     24000  46000         9.1
3    Ivan  Odesa      9500     14000  23500        47.4

### Завдання 39

Додай до DataFrame `df` стовпець `delta`.

Він має дорівнювати різниці:

```python
sales_q2 - sales_q1
```

In [154]:
# Завдання 39

df['delta'] = df['sales_q2'] - df['sales_q1']
df

  manager region  sales_q1  sales_q2  total  growth_pct  delta
0    Anna   Kyiv     15000     17000  32000        13.3   2000
1  Bohdan   Lviv     12000     11000  23000        -8.3  -1000
2   Olena   Kyiv     22000     24000  46000         9.1   2000
3    Ivan  Odesa      9500     14000  23500        47.4   4500

### Завдання 40

Створи DataFrame `above_average_total`.

У ньому мають бути тільки ті менеджери, у яких `total` більше за середнє значення `total` по всій команді.

In [155]:
# Завдання 40

# avg is average of column 'total'
avg = df['total'].mean()
above_average_total = df[df['total'] > avg]
above_average_total

  manager region  sales_q1  sales_q2  total  growth_pct  delta
0    Anna   Kyiv     15000     17000  32000        13.3   2000
2   Olena   Kyiv     22000     24000  46000         9.1   2000

### Завдання 41

Створи DataFrame `declined_df`.

У ньому мають бути тільки ті менеджери, у яких `growth_pct` менше за 0.

In [156]:
# Завдання 41

declined_df = df[df['growth_pct'] < 0]
declined_df

  manager region  sales_q1  sales_q2  total  growth_pct  delta
1  Bohdan   Lviv     12000     11000  23000        -8.3  -1000

### Завдання 42

Створи DataFrame `kyiv_df`.

У ньому мають бути тільки менеджери з регіону `'Kyiv'`.

In [157]:
# Завдання 42

kyiv_df = df[df['region'] == 'Kyiv']
kyiv_df

  manager region  sales_q1  sales_q2  total  growth_pct  delta
0    Anna   Kyiv     15000     17000  32000        13.3   2000
2   Olena   Kyiv     22000     24000  46000         9.1   2000

### Завдання 43

Створи DataFrame `manager_total`.

У ньому мають бути тільки два стовпці:

1. `manager`
2. `total`

Використай подвійні квадратні дужки.

In [158]:
# Завдання 43

manager_total = df[['manager', 'total']]
manager_total

  manager  total
0    Anna  32000
1  Bohdan  23000
2   Olena  46000
3    Ivan  23500

### Завдання 44

Створи DataFrame `top_total`.

У ньому менеджери мають бути відсортовані за `total` від найбільшого до найменшого.

Використай `.sort_values()`.

In [159]:
# Завдання 44

top_total = df.sort_values(by='total', ascending=False)
top_total

  manager region  sales_q1  sales_q2  total  growth_pct  delta
2   Olena   Kyiv     22000     24000  46000         9.1   2000
0    Anna   Kyiv     15000     17000  32000        13.3   2000
3    Ivan  Odesa      9500     14000  23500        47.4   4500
1  Bohdan   Lviv     12000     11000  23000        -8.3  -1000

### Завдання 45

Збережи фінальний DataFrame `df` у файл `sales_analysis.csv`.

Файл потрібно зберегти без індексу.

In [160]:
# Завдання 45

df.to_csv('sales_analysis.csv', index=False)

### Завдання 46

Зчитай файл `sales_analysis.csv` у змінну `df_check`.

In [161]:
# Завдання 46

df_check = pd.read_csv('sales_analysis.csv')
df_check

  manager region  sales_q1  sales_q2  total  growth_pct  delta
0    Anna   Kyiv     15000     17000  32000        13.3   2000
1  Bohdan   Lviv     12000     11000  23000        -8.3  -1000
2   Olena   Kyiv     22000     24000  46000         9.1   2000
3    Ivan  Odesa      9500     14000  23500        47.4   4500

### Завдання 47

Створи змінну `shapes_match`.

Вона має дорівнювати `True`, якщо форма `df_check` збігається з формою `df`.

In [162]:
# Завдання 47

shapes_match = df.shape == df_check.shape
shapes_match

True