Використай цей шаблон в роботі з датасетом.     
Обмежся функціями з наведених бібліотек.

In [36]:
import pandas as pd
import seaborn as sns

## Частина 1. Завантаження та первинне дослідження даних

1. Завантаж датасет `titanic` з бібліотеки seaborn у змінну `df`.

In [37]:
# Завдання 1

df = sns.load_dataset('titanic')
df.shape

(891, 15)

2. Переглянь перші рядки датасету. Зроби висновок, чи коректно він завантажився.

In [38]:
# Завдання 2
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

3. Перевір типи стовпців. Які з них потребують перетворення?

In [39]:
# Завдання 3

df.dtypes
df.info()
# Потребують перетворення:
# Текстові стовпчики sex, embarked, embark_town, who, alive (зараз object) —
# їх варто перевести в category, щоб зекономити пам'ять.
# pclass (зараз int64) — за змістом це клас квитка (категорія), тому його теж краще перевести в category або object.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

4. Перевір статистику за всіма стовпцями датасету.

In [40]:
# Завдання 4

df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Частина 2. Створення нових ознак та аналіз родинних зв'язків

5. Необхідно створити єдиний стовпчик 'relatives', що вказує кількість родичів для кожного пасажира на борту, замість:
- кількість братів/сестер або чоловіків/дружин на борту;
- кількість батьків або дітей на борту;

Булева ознака: стовпчик 'alone'=True, якщо пасажир подорожував один (без родичів на борту).    
Перевір, щоб для одиноких пасажирів новий стовпчик мав значення 0.   
Після створення нового стовпчика, дропни "sibsp", "parch", "alone".     
Порахуй кількість пропущених значень (NaN) у стовпці relatives, збережи результат у змінну та виведи її.

In [41]:
# Завдання 5

df['relatives'] = df['sibsp'] + df['parch']
print(df.loc[df['alone'] == True, 'relatives'].value_counts())
df = df.drop(columns=['sibsp', 'parch', 'alone'])
nan_relatives = df['relatives'].isna().sum()
print("Кількість NaN у стовпчику relatives:", nan_relatives)
display(df)

relatives
0    537
Name: count, dtype: int64
Кількість NaN у стовпчику relatives: 0

,survived,pclass,sex,age,fare,embarked,class,who,adult_male,deck,embark_town,alive,relatives
0,0,3,male,22.0,7.2500,S,Third,man,True,NaN,Southampton,no,1
1,1,1,female,38.0,71.2833,C,First,woman,False,C,Cherbourg,yes,1
2,1,3,female,26.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,0
3,1,1,female,35.0,53.1000,S,First,woman,False,C,Southampton,yes,1
4,0,3,male,35.0,8.0500,S,Third,man,True,NaN,Southampton,no,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,13.0000,S,Second,man,True,NaN,Southampton,no,0
887,1,1,female,19.0,30.0000,S,First,woman,False,B,Southampton,yes,0
888,0,3,female,NaN,23.4500,S,Third,woman,False,NaN,Southampton,no,3
889,1,1,male,26.0,30.0000,C,First,man,True,C,Cherbourg,yes,0
890,0,3,male,32.0,7.7500,Q,Third,man,True,NaN,Queenstown,no,0

6. Перевір, як часто зустрічається певна кількість родичів в новому стовпці.     
Як результат, створи та відобрази DataFrame з частотою появи кожного значення `relatives`, використовуючи групування та агрегацію.

In [42]:
# Завдання 6

# (df['relatives'].value_counts())
# df.relatives.value_counts()
relatives_frequence = df.groupby('relatives').size().reset_index(name='frequency')
display(relatives_frequence)

   relatives  frequency
0          0        537
1          1        161
2          2        102
3          3         29
4          4         15
5          5         22
6          6         12
7          7          6
8         10          7

7. Використовуючи цикл заміни кількість родичів, що перевищує число 5(п'ять) на значення "above 5"(понад п'ять).       
Запиши значення в новий стовпчик ʼrelatives_categoryʼ.     
Як результат, створи та відобрази DataFrame з частотою появи кожного значення `relatives_category`, використовуючи групування та агрегацію.

In [43]:
# Завдання 7
relatives_category = []
for iii in df.relatives:
  if iii <= 5:
    relatives_category.append(str(iii))
  else:
    relatives_category.append('above 5')
df['relatives_category'] = relatives_category
relatives_category = df.groupby('relatives_category').size().reset_index(name='frequency')
display(relatives_category)

  relatives_category  frequency
0                  0        537
1                  1        161
2                  2        102
3                  3         29
4                  4         15
5                  5         22
6            above 5         25

## Частина 3. Групування та статистика за портами посадки

8. Необхідно вивести на екран статистику по відсотковому показнику пасажирів з кількістю родичів більше 5 відносно загального числа пасажирів для кожного з міст посадки. Для цього:
- порахуй загальну кількість пасажирів в кожному з міст посадки,
- знайди число пасажирів з кількістю родичів більше 5 в кожному з міст посадки (якщо таких пасажирів немає, використай значення 0),
- поділи ці два стовпчики між собою, перетворивши результат у відсотки (ціле число).

Як результат, створи та відобрази DataFrame для кожного міста посадки, що містить усі розраховані показники.

In [58]:
# Завдання 8

embark_town_count = df.groupby('embark_town').size().reset_index(name='amount_passangers')
# display(embark_town_count)
df_above5 = df[df['relatives_category'] == 'above 5']
above5_count = df_above5.groupby('embark_town').size().reset_index(name='amount_passangers_above5')
# display(above5_count)
amount_above5_embark = embark_town_count.merge(above5_count, on='embark_town', how='left')
amount_above5_embark['amount_passangers_above5'] = amount_above5_embark['amount_passangers_above5'].fillna(0)
amount_above5_embark['percentage'] = (amount_above5_embark['amount_passangers_above5'] / amount_above5_embark['amount_passangers'] * 100).astype(int)
display(amount_above5_embark)

   embark_town  amount_passangers  amount_passangers_above5  percentage
0    Cherbourg                168                       0.0           0
1   Queenstown                 77                       0.0           0
2  Southampton                644                      25.0           3

## Частина 4. Обробка та категоризація віку

9. Заповни відсутні значення віку медіаною.

In [45]:
# Завдання 9

median_age = df['age'].median()
display(median_age)
df['age'].isna().sum()
print("Кількість NaN до заповнення:", df['age'].isna().sum())
df['age'] = df['age'].fillna(median_age)
df['age'].isna().sum()
print("Кількість NaN після заповнення:", df['age'].isna().sum())
display(df)

28.0

Кількість NaN до заповнення: 177
Кількість NaN після заповнення: 0

,survived,pclass,sex,age,fare,embarked,class,who,adult_male,deck,embark_town,alive,relatives,relatives_category
0,0,3,male,22.0,7.2500,S,Third,man,True,NaN,Southampton,no,1,1
1,1,1,female,38.0,71.2833,C,First,woman,False,C,Cherbourg,yes,1,1
2,1,3,female,26.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,0,0
3,1,1,female,35.0,53.1000,S,First,woman,False,C,Southampton,yes,1,1
4,0,3,male,35.0,8.0500,S,Third,man,True,NaN,Southampton,no,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,13.0000,S,Second,man,True,NaN,Southampton,no,0,0
887,1,1,female,19.0,30.0000,S,First,woman,False,B,Southampton,yes,0,0
888,0,3,female,28.0,23.4500,S,Third,woman,False,NaN,Southampton,no,3,3
889,1,1,male,26.0,30.0000,C,First,man,True,C,Cherbourg,yes,0,0
890,0,3,male,32.0,7.7500,Q,Third,man,True,NaN,Queenstown,no,0,0

10. Створи новий стовпець, де вік представлено категорією, замість числа (категорії: до 14 років, 14-34 роки, 35-59 років, 60 і більше років). Категорії: `child`, `young`, `adult`, `senior`.   
Як результат, створи та відобрази DataFrame з кількістю пасажирів для кожного значення `age_group`.

In [46]:
from pandas.core.indexes import category
# Завдання 10

df.loc[df['age'] < 14, 'age_group'] = 'child'
df.loc[(df['age'] >= 14) & (df['age'] < 35), 'age_group'] = 'young'
df.loc[(df['age'] >= 35) & (df['age'] < 60), 'age_group'] = 'adult'
df.loc[df['age'] >= 60 , 'age_group'] = 'senior'
df['age_group'] = df['age_group'].astype('category')
# age_group_count = df.groupby('age_group',observed=False).size().reset_index(name='age_group_count').sort_values(by='age_group_count', ascending=False)
age_group_count = df['age_group'].value_counts().reset_index(name='age_group_count')
display(age_group_count)

  age_group  age_group_count
0     young              585
1     adult              209
2     child               71
3    senior               26

## Частина 5. Аналіз виживання пасажирів

11. Перевір, в якій віковій категорії була найвища смертність. Для цього створи окремий булевий стовпець для пасажирів, які не вижили, використовуючи значення стовпця `alive`.       
Для кожної вікової категорії підрахуй:
- загальну кількість пасажирів;
- кількість пасажирів, які не вижили;
- відсоток пасажирів, які не вижили.    
Як результат, створи та відобрази DataFrame, де для кожної вікової категорії наведені всі розраховані показники.

In [56]:
# Завдання 11

df['not_survived'] = df['alive'] == 'no'
survival_by_age = df.groupby('age_group', observed=False)['not_survived'].agg(total_passengers='count', not_survived_count='sum', not_survived_percentage='mean').reset_index()
survival_by_age['not_survived_percentage'] = (survival_by_age['not_survived_percentage'] *100).round(2)
display(survival_by_age)

  age_group  total_passengers  not_survived_count  not_survived_percentage
0     adult               209                 122                    58.37
1     child                71                  29                    40.85
2    senior                26                  19                    73.08
3     young               585                 379                    64.79